config_version = 13

[accessibility]
ui_scale = 1.0

[audio]
enable_sounds = true

[bar]
order = [ "cyberrr" ]

    [bar.cyberrr]
    background_opacity = 0.4999999888241291
    border = "surface"
    border_width = 1.0
    capsule = true
    capsule_fill = "on_primary"
    capsule_opacity = 0.60999998636543751
    capsule_padding = 5.0
    capsule_thickness = 0.70999998785555363
    center = [ "audio_visualizer", "clock", "weather" ]
    end = [ "clipboard", "ram", "bluetooth", "network", "battery", "session" ]
    font_family = "Adwaita Sans"
    font_weight = 400
    margin_ends = 130
    padding = 8
    panel_overlap = 0
    radius = 40
    radius_bottom_left = 45
    radius_bottom_right = 45
    radius_top_left = 45
    radius_top_right = 45
    reserve_space = true
    scale = 0.90000000596046448
    shadow = false
    start = [ "workspaces", "active_window" ]
    widget_spacing = 4

[battery]
warning_threshold = 15

[brightness]
minimum_brightness = 0.01

[control_center]
sidebar_section = "full"
width = 800

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "nightlight"

    [[control_center.shortcuts]]
    type = "notification"

    [[control_center.shortcuts]]
    type = "wallpaper"

    [[control_center.shortcuts]]
    type = "session"

[dock]
active_scale = 1.2000000178813934
background_opacity = 0.0
border = "#5A5959"
border_width = 1.0
cross_axis_padding = 0
enabled = false
inactive_opacity = 1.0
item_spacing = 0
launcher_position = "start"
main_axis_padding = 8
margin_edge = 8
pinned = [
    "app.zen_browser.zen",
    "org.gnome.Nautilus",
    "kitty",
    "md.obsidian.Obsidian",
    "org.videolan.VLC",
    "org.telegram.desktop",
    "com.bilingify.readest",
    "com.bitwarden.desktop",
    "org.gnome.Loupe",
    "org.gnome.Papers",
    "gimp",
    "dev.noctalia.Noctalia"
]
radius = 23
reserve_space = false
show_dots = true
smart_auto_hide = true

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 300.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 600.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 900.0

[location]
auto_locate = true

[lockscreen]
blur_intensity = 0.1099999975413084
tint_intensity = 0.14999999999999999
wallpaper = "/home/cyber/Pictures/wallpapers/65626-2048x1536-desktop-hd-british-cat-background-photo.jpg"

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1", "lockscreen-widget-0000000000000001" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 260.0
    cx = 683.0
    cy = 440.0
    output = "eDP-1"
    placement_height = 768.0
    placement_width = 1366.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.40000000000000002
        background_radius = 10.0
        center_password_text = true
        input_opacity = 0.80000000000000004
        input_radius = 5.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = false
        show_login_button = false
        show_media = false
        show_session_buttons = false
        show_unlock_hint = true
        show_weather = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 120.0
    box_width = 240.0
    cx = 683.0
    cy = 280.0
    output = "eDP-1"
    placement_height = 768.0
    placement_width = 1366.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background_color = "surface_variant"
        background_opacity = 0.30000000000000004
        center_text = true
        clock_style = "digital"

[notification]
background_opacity = 0.50999998860061169

[osd]
background_opacity = 0.29999999329447746
scale = 0.85000000521540642

[shell]
app_icon_color = "primary"
avatar_path = "/home/cyber/Downloads/cat2.jpeg"
clipboard_confirm_clear_history = false
corner_radius_scale = 1.5000000223517418
font_family = "Adwaita Sans"
niri_overview_type_to_launch_enabled = true
password_style = "random"
polkit_agent = true
screen_time_enabled = true

    [shell.launcher]
    app_grid = true
    categories = false

    [shell.panel]
    borders = false
    open_near_click_control_center = true
    session_placement = "floating"
    session_position = "center"
    transparency_mode = "glass"

    [shell.screen_corners]
    enabled = true
    size = 11

    [shell.session]
    show_shortcuts = false

[theme]
builtin = "Ayu"
community_palette = "GruvboxAlt"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "soft"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "kcolorscheme", "kitty", "niri", "qt" ]
    community_ids = [ "opencode", "zed" ]

[wallpaper]
directory_dark = "/home/cyber/Pictures/wallpapers"
directory_light = "/home/cyber/Pictures/wallpapers/Pc-Wallpapers"
edge_smoothness = 0.29999999329447746
transition_duration = 2000
transition_on_startup = true

    [wallpaper.default]
    path = "/home/cyber/Pictures/wallpapers/1004017-colorized.png"

    [wallpaper.last]
    path = "/home/cyber/Pictures/wallpapers/1004017-colorized.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/cyber/Pictures/wallpapers/1004017-colorized.png"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/cyber/Pictures/wallpapers/1.png"
    theme_mode = "dark"
    wallpaper_scheme = "vibrant"

    [[wallpaper.favorite]]
    builtin_palette = "Ayu"
    palette_source = "builtin"
    path = "/home/cyber/Pictures/wallpapers/daniel-leone-v7daTKlZzaw-unsplash.jpg"
    theme_mode = "dark"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/cyber/Pictures/wallpapers/balancing-rocks-5120x2880-16599.jpg"
    theme_mode = "dark"
    wallpaper_scheme = "vibrant"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/cyber/Pictures/wallpapers/castle-oil-painting.png"
    theme_mode = "dark"
    wallpaper_scheme = "vibrant"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/cyber/Pictures/wallpapers/dinosaur-kid-night-travel-discover-moon-silhouette-3500x3000-1057.jpg"
    theme_mode = "dark"
    wallpaper_scheme = "dysfunctional"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/cyber/Pictures/wallpapers/girl-walking-streets.png"
    theme_mode = "dark"
    wallpaper_scheme = "vibrant"

    [[wallpaper.favorite]]
    builtin_palette = "Ayu"
    palette_source = "builtin"
    path = "/home/cyber/Pictures/wallpapers/killer-king.jpg"
    theme_mode = "dark"

    [[wallpaper.favorite]]
    builtin_palette = "Gruvbox"
    palette_source = "builtin"
    path = "/home/cyber/Pictures/wallpapers/my1.jpg"
    theme_mode = "dark"

    [[wallpaper.favorite]]
    builtin_palette = "Gruvbox"
    palette_source = "builtin"
    path = "/home/cyber/Pictures/wallpapers/peaky-blinders-the-3840x2160-25562.jpg"
    theme_mode = "dark"

    [[wallpaper.favorite]]
    builtin_palette = "Ayu"
    palette_source = "builtin"
    path = "/home/cyber/Pictures/wallpapers/the-odyssey-7680x4320-25035.jpg"
    theme_mode = "dark"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/cyber/Pictures/wallpapers/my 7.png"
    theme_mode = "dark"
    wallpaper_scheme = "vibrant"

[weather]
enabled = true
refresh_minutes = 30
unit = "celsius"

[widget.active_window]
display = "app_icon_color,center_text"
enabled = true
icon_size = 20
max_length = 90
min_length = 16
scale = 1.0
show_empty_label = false
title_scroll = "none"

[widget.audio_visualizer]
bands = 11
capsule_padding = 0
color_1 = "tertiary"
enabled = false
scale = 1.3500000000000001
width = 55

[widget.battery]
capsule = true
capsule_padding = 7
display_mode = "graphic"
scale = 0.94999999999999996

[widget.bluetooth]
scale = 1.05

[widget.brightness]
scale = 1.05

[widget.clipboard]
scale = 1.05

[widget.clock]
capsule = true
capsule_padding = 11
font_weight = 600
format = "{:%a %d %b   %H:%M}"

[widget.media]
art_size = 18
artist_first = true
enabled = true
hide_when_no_media = true
max_length = 24
title_scroll = "on_hover"

[widget.network]
capsule = true
capsule_padding = 9
scale = 1.05

[widget.ram]
glyph = ""
label_show_units = true
scale = 0.94999999999999996
show_glyph = true
show_value = true
stat = "ram_pct"
type = "sysmon"
visualization = "none"

[widget.session]
enabled = false
scale = 1.05

[widget.volume]
enabled = false

[widget.weather]
capsule = true
capsule_padding = 8
enabled = false
max_length = 24
show_condition = false
show_temperature = true

[widget.workspaces]
active_pill_size = 2.1000000000000001
capsule_radius = 80
change_color_on_hover = true
empty_color = "#4C566A"
focused_color = "#EB8554"
inactive_pill_size = 1.4500000000000002
occupied_color = "#33A1BE"
pill_scale = 0.84999999999999998
scale = 1.2
style = "minimal"
urgent_color = "#BF616A"